### ISSUE TITLE
tsのターゲットをes2020にする

### ISSUE THREAD

**Issue by ssssota** [nori3636/discordbot_codehighlight#11]
es5が指定されているが、node v16↑でしか動かないのでes5である必要がない（v16はes2021までサポートされている ref. https://node.green/#ES2021 ）

es5にすると互換性のために冗長なコードが生成される

**Comment by norikmb** [comment]
対応しました

**Comment by ssssota** [comment]
@nori3636 対応したものについては閉じていただいて結構です
