### ISSUE TITLE
生成されたファイルがgitで管理されている

### ISSUE THREAD

**Issue by ssssota** [nori3636/discordbot_codehighlight#6]
`src/index.js` はtscで生成されるファイル

再現可能であるためgit管理は不要

**Comment by norikmb** [comment]
対応しました

**Comment by ssssota** [comment]
https://github.com/nori3636/discordbot_codehighlight/blob/ec0a2213fbb7fc11b2e45de802eaadff20ba01d3/.gitignore#L2

**Comment by norikmb** [comment]
ignoreの書き方を変えました

**Comment by norikmb** [comment]
git rm --cached src/index.js しました

**Comment by ssssota** [comment]
作業内容自体はソースコードで見えてます
draft PRつくってlinkしてください

**Comment by norikmb** [comment]
リンクしました
